apiVersion: v1
kind: Service
metadata:
  name: golang-server-service
  namespace: development
spec:
  selector:
    app: golang-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
