apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: development
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16 # Use the appropriate version
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "horsemktuser"
        - name: POSTGRES_PASSWORD
          value: "@EUZ29tmw-yr2jnZY8M@"
        - name: POSTGRES_DB
          value: "horsemktdb"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
