// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/repositories/password_reset.go

// Package mockrepositories is a generated GoMock package.
package mockrepositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/hfleury/horsemarketplacebk/internal/auth/models"
)

// MockPasswordResetRepository is a mock of PasswordResetRepository interface.
type MockPasswordResetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResetRepositoryMockRecorder
}

// MockPasswordResetRepositoryMockRecorder is the mock recorder for MockPasswordResetRepository.
type MockPasswordResetRepositoryMockRecorder struct {
	mock *MockPasswordResetRepository
}

// NewMockPasswordResetRepository creates a new mock instance.
func NewMockPasswordResetRepository(ctrl *gomock.Controller) *MockPasswordResetRepository {
	mock := &MockPasswordResetRepository{ctrl: ctrl}
	mock.recorder = &MockPasswordResetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResetRepository) EXPECT() *MockPasswordResetRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPasswordResetRepository) Create(ctx context.Context, pr *models.PasswordReset) (*models.PasswordReset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pr)
	ret0, _ := ret[0].(*models.PasswordReset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPasswordResetRepositoryMockRecorder) Create(ctx, pr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPasswordResetRepository)(nil).Create), ctx, pr)
}

// GetLatestByUserID mocks base method.
func (m *MockPasswordResetRepository) GetLatestByUserID(ctx context.Context, userID string) (*models.PasswordReset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestByUserID", ctx, userID)
	ret0, _ := ret[0].(*models.PasswordReset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestByUserID indicates an expected call of GetLatestByUserID.
func (mr *MockPasswordResetRepositoryMockRecorder) GetLatestByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestByUserID", reflect.TypeOf((*MockPasswordResetRepository)(nil).GetLatestByUserID), ctx, userID)
}

// MarkAsUsed mocks base method.
func (m *MockPasswordResetRepository) MarkAsUsed(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsUsed", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsUsed indicates an expected call of MarkAsUsed.
func (mr *MockPasswordResetRepositoryMockRecorder) MarkAsUsed(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsUsed", reflect.TypeOf((*MockPasswordResetRepository)(nil).MarkAsUsed), ctx, token)
}

// SelectByToken mocks base method.
func (m *MockPasswordResetRepository) SelectByToken(ctx context.Context, token string) (*models.PasswordReset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByToken", ctx, token)
	ret0, _ := ret[0].(*models.PasswordReset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByToken indicates an expected call of SelectByToken.
func (mr *MockPasswordResetRepositoryMockRecorder) SelectByToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByToken", reflect.TypeOf((*MockPasswordResetRepository)(nil).SelectByToken), ctx, token)
}
