// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/repositories/email_verification.go

// Package mockrepositories is a generated GoMock package.
package mockrepositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/hfleury/horsemarketplacebk/internal/auth/models"
)

// MockEmailVerificationRepository is a mock of EmailVerificationRepository interface.
type MockEmailVerificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailVerificationRepositoryMockRecorder
}

// MockEmailVerificationRepositoryMockRecorder is the mock recorder for MockEmailVerificationRepository.
type MockEmailVerificationRepositoryMockRecorder struct {
	mock *MockEmailVerificationRepository
}

// NewMockEmailVerificationRepository creates a new mock instance.
func NewMockEmailVerificationRepository(ctrl *gomock.Controller) *MockEmailVerificationRepository {
	mock := &MockEmailVerificationRepository{ctrl: ctrl}
	mock.recorder = &MockEmailVerificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailVerificationRepository) EXPECT() *MockEmailVerificationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEmailVerificationRepository) Create(ctx context.Context, ev *models.EmailVerification) (*models.EmailVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ev)
	ret0, _ := ret[0].(*models.EmailVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEmailVerificationRepositoryMockRecorder) Create(ctx, ev interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEmailVerificationRepository)(nil).Create), ctx, ev)
}

// GetLatestByEmail mocks base method.
func (m *MockEmailVerificationRepository) GetLatestByEmail(ctx context.Context, email string) (*models.EmailVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestByEmail", ctx, email)
	ret0, _ := ret[0].(*models.EmailVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestByEmail indicates an expected call of GetLatestByEmail.
func (mr *MockEmailVerificationRepositoryMockRecorder) GetLatestByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestByEmail", reflect.TypeOf((*MockEmailVerificationRepository)(nil).GetLatestByEmail), ctx, email)
}

// MarkVerified mocks base method.
func (m *MockEmailVerificationRepository) MarkVerified(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkVerified", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkVerified indicates an expected call of MarkVerified.
func (mr *MockEmailVerificationRepositoryMockRecorder) MarkVerified(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkVerified", reflect.TypeOf((*MockEmailVerificationRepository)(nil).MarkVerified), ctx, token)
}

// SelectByToken mocks base method.
func (m *MockEmailVerificationRepository) SelectByToken(ctx context.Context, token string) (*models.EmailVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByToken", ctx, token)
	ret0, _ := ret[0].(*models.EmailVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByToken indicates an expected call of SelectByToken.
func (mr *MockEmailVerificationRepositoryMockRecorder) SelectByToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByToken", reflect.TypeOf((*MockEmailVerificationRepository)(nil).SelectByToken), ctx, token)
}
