// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/repositories/session.go

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionRepository) Create(ctx context.Context, userID string, sessionToken string, expiresAt string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, sessionToken, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryMockRecorder) Create(ctx, userID, sessionToken, expiresAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepository)(nil).Create), ctx, userID, sessionToken, expiresAt)
}

// Validate mocks base method.
func (m *MockSessionRepository) Validate(ctx context.Context, sessionToken string) (string, bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, sessionToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Validate indicates an expected call of Validate.
func (mr *MockSessionRepositoryMockRecorder) Validate(ctx, sessionToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockSessionRepository)(nil).Validate), ctx, sessionToken)
}

// Revoke mocks base method.
func (m *MockSessionRepository) Revoke(ctx context.Context, sessionToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, sessionToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockSessionRepositoryMockRecorder) Revoke(ctx, sessionToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockSessionRepository)(nil).Revoke), ctx, sessionToken)
}

// RevokeAllForUser mocks base method.
func (m *MockSessionRepository) RevokeAllForUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllForUser indicates an expected call of RevokeAllForUser.
func (mr *MockSessionRepositoryMockRecorder) RevokeAllForUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForUser", reflect.TypeOf((*MockSessionRepository)(nil).RevokeAllForUser), ctx, userID)
}

// Rotate mocks base method.
func (m *MockSessionRepository) Rotate(ctx context.Context, userID string, oldToken string, newToken string, newExpiry string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rotate", ctx, userID, oldToken, newToken, newExpiry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rotate indicates an expected call of Rotate.
func (mr *MockSessionRepositoryMockRecorder) Rotate(ctx, userID, oldToken, newToken, newExpiry interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rotate", reflect.TypeOf((*MockSessionRepository)(nil).Rotate), ctx, userID, oldToken, newToken, newExpiry)
}
